source 'https://github.com/CocoaPods/Specs.git'
source 'https://gitee.com/rrrmmmhhh/RMHComponentSpecs.git'
#use_frameworks!

target 'RMHBase_Example' do
  pod 'RMHBase', :path => '../'
  pod 'AFNetworking'
  pod 'JSONModel'
  pod  'SDWebImage'
  target 'RMHBase_Tests' do
    inherit! :search_paths

    
  end
end
