# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "AutomationLib"
  lane :AutomationLib do |options|
    tagName = options[:tag]
    targetName = options[:target]
    
    # 1. pod install
    cocoapods(
    clean: true,
    podfile: "./Example/Podfile"
    )
    
    
    
    # 2. git add .
    git_add(path: ".")
    #    git commit -m 'xxx'
    git_commit(path: ".", message: "update lib")
    #    git push origin master
    push_to_git_remote
    
    
    if git_tag_exists(tag: tagName)
        UI.message("discover tag:#{tagName} already existed, be about to delete action 🚀")
        remove_tag(tag:tagName)
    end
    
    add_git_tag(
    tag: tagName
    )
    
    #    git push --tags
    push_git_tags
    
    # 4. pod spec lint
    pod_lib_lint(allow_warnings: true)
    
    #    pod repo push XXXX xxx.podspec
    pod_push(path: "#{targetName}.podspec", repo: "RMHBaseSpec", allow_warnings: true)
    
  end
end
